global:
    scrape_interval: 15s
    evaluation_interval: 15s
    
scrape_configs:
    - job_name: "testando prometheus"
      metrics_path: "/actuator/prometheus"
      scrape_interval: 
      static_configs:
          - targets: ["host.docker.internal:8081"]
            labels:
                application: "usuarios"
        